### ISSUE TITLE
Lotus Eth JSON-RPC API: eth_getTransactionByHash returns null for pending tx, prevents `forge create` from deploying

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/ref-fvm#1196]
I tried to use `forge create` to deploy to Wallaby:

https://book.getfoundry.sh/forge/deploying

```
$ forge init hello_foundry
Initializing /Users/jim/fvm-jpimac/localnet-farm/hello_foundry...
Installing forge-std in "/Users/jim/fvm-jpimac/localnet-farm/hello_foundry/lib/forge-std" (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
    Installed forge-std v1.1.1
    Initialized forge project.
    
$ cd hello_foundry

$ forge build
[⠢] Compiling...
[⠔] Compiling 18 files with 0.8.15
[⠑] Solc 0.8.15 finished in 2.21s
Compiler run successful

$ forge create --rpc-url https://wallaby.node.glif.io --private-key <private-key> src/Counter.sol:Counter
[⠆] Compiling...
No files changed, compilation skipped
Error: 
Contract was not deployed
```

The deploy failed.

Same deploy to Goerli:

```
$ forge create --rpc-url https://eth-goerli.g.alchemy.com/v2/<api-key> --private-key <private-key> src/Counter.sol:Counter
[⠆] Compiling...
No files changed, compilation skipped
Deployer: 0x75045AFcc7Cd37e6A93513b97bAaAA8D0c848e07
Deployed to: 0x68e1dB96944Cb9f2EB844Fb2677B768864384A00
Transaction hash: 0x8f0ffe044bbf83b73693779dec238b0e9a08ffc7ac0ee2d4f99e9be984258b66
```

Goerli succeeds where Wallaby didn't.

I did some tracing and there are some differences on the wire with the JSON-RPC requests/responses:

Goerli:

```
$ RUST_LOG=trace forge create --rpc-url https://eth-goerli.g.alchemy.com/v2/<api-key> --private-key <private-key> src/Counter.sol:Counter 2>&1 | tee goerli.log
<tee output>

$ grep 'rpc.*rx' goerli.log | grep -A5 'eth_sendRawTransaction'
2022-12-04T20:37:00.183722Z TRACE rpc{method="eth_sendRawTransaction" params="[\"0x02f9016f050884b2d05e0084b2d05e108301a0df8080b90116608060405234801561001057600080fd5b5060f78061001f6000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80633fb5c1cb1460415780638381f58a146053578063d09de08a14606d575b600080fd5b6051604c3660046083565b600055565b005b605b60005481565b60405190815260200160405180910390f35b6051600080549080607c83609b565b9190505550565b600060208284031215609457600080fd5b5035919050565b60006001820160ba57634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212204ae8109ae428574ea5c6c4840c0c8dcec482287baa69f00b5e4df2bf104a50df64736f6c634300080f0033c080a074c7bf4e3ed9069a3dbb573f3c0e98f0b0b343cdcf733c8af23102695317796ba07be832b3cd5ceae3c65165213f5818bf9350307c490a26c6e5ded1f747363b08\"]"}: ethers_providers::provider: rx="\"0xfcf8b4ce53aed1a9c5b900fba738cbd5ffd45b23fcbd4efb7f026cb7ff04e23b\""
2022-12-04T20:37:06.800618Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0xfcf8b4ce53aed1a9c5b900fba738cbd5ffd45b23fcbd4efb7f026cb7ff04e23b\"]"}: ethers_providers::provider: rx="{\"hash\":\"0xfcf8b4ce53aed1a9c5b900fba738cbd5ffd45b23fcbd4efb7f026cb7ff04e23b\",\"nonce\":\"0x8\",\"blockHash\":null,\"blockNumber\":null,\"transactionIndex\":null,\"from\":\"0x75045afcc7cd37e6a93513b97baaaa8d0c848e07\",\"to\":null,\"value\":\"0x0\",\"gasPrice\":\"0xb2d05e10\",\"gas\":\"0x1a0df\",\"input\":\"0x608060405234801561001057600080fd5b5060f78061001f6000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80633fb5c1cb1460415780638381f58a146053578063d09de08a14606d575b600080fd5b6051604c3660046083565b600055565b005b605b60005481565b60405190815260200160405180910390f35b6051600080549080607c83609b565b9190505550565b600060208284031215609457600080fd5b5035919050565b60006001820160ba57634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212204ae8109ae428574ea5c6c4840c0c8dcec482287baa69f00b5e4df2bf104a50df64736f6c634300080f0033\",\"v\":\"0x0\",\"r\":\"0x74c7bf4e3ed9069a3dbb573f3c0e98f0b0b343cdcf733c8af23102695317796b\",\"s\":\"0x7be832b3cd5ceae3c65165213f5818bf9350307c490a26c6e5ded1f747363b08\",\"type\":\"0x2\",\"accessList\":[],\"maxPriorityFeePerGas\":\"0xb2d05e00\",\"maxFeePerGas\":\"0xb2d05e10\",\"chainId\":\"0x5\"}"
2022-12-04T20:37:13.407036Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0xfcf8b4ce53aed1a9c5b900fba738cbd5ffd45b23fcbd4efb7f026cb7ff04e23b\"]"}: ethers_providers::provider: rx="{\"hash\":\"0xfcf8b4ce53aed1a9c5b900fba738cbd5ffd45b23fcbd4efb7f026cb7ff04e23b\",\"nonce\":\"0x8\",\"blockHash\":null,\"blockNumber\":null,\"transactionIndex\":null,\"from\":\"0x75045afcc7cd37e6a93513b97baaaa8d0c848e07\",\"to\":null,\"value\":\"0x0\",\"gasPrice\":\"0xb2d05e10\",\"gas\":\"0x1a0df\",\"input\":\"0x608060405234801561001057600080fd5b5060f78061001f6000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80633fb5c1cb1460415780638381f58a146053578063d09de08a14606d575b600080fd5b6051604c3660046083565b600055565b005b605b60005481565b60405190815260200160405180910390f35b6051600080549080607c83609b565b9190505550565b600060208284031215609457600080fd5b5035919050565b60006001820160ba57634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212204ae8109ae428574ea5c6c4840c0c8dcec482287baa69f00b5e4df2bf104a50df64736f6c634300080f0033\",\"v\":\"0x0\",\"r\":\"0x74c7bf4e3ed9069a3dbb573f3c0e98f0b0b343cdcf733c8af23102695317796b\",\"s\":\"0x7be832b3cd5ceae3c65165213f5818bf9350307c490a26c6e5ded1f747363b08\",\"type\":\"0x2\",\"accessList\":[],\"maxPriorityFeePerGas\":\"0xb2d05e00\",\"maxFeePerGas\":\"0xb2d05e10\",\"chainId\":\"0x5\"}"
2022-12-04T20:37:20.024465Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0xfcf8b4ce53aed1a9c5b900fba738cbd5ffd45b23fcbd4efb7f026cb7ff04e23b\"]"}: ethers_providers::provider: rx="{\"hash\":\"0xfcf8b4ce53aed1a9c5b900fba738cbd5ffd45b23fcbd4efb7f026cb7ff04e23b\",\"nonce\":\"0x8\",\"blockHash\":\"0x433201abbef3437ad893cb0789185280a267a1111f0a0e4689bc5d11edc36926\",\"blockNumber\":\"0x7b36f6\",\"transactionIndex\":\"0x1\",\"from\":\"0x75045afcc7cd37e6a93513b97baaaa8d0c848e07\",\"to\":null,\"value\":\"0x0\",\"gasPrice\":\"0xb2d05e08\",\"gas\":\"0x1a0df\",\"input\":\"0x608060405234801561001057600080fd5b5060f78061001f6000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80633fb5c1cb1460415780638381f58a146053578063d09de08a14606d575b600080fd5b6051604c3660046083565b600055565b005b605b60005481565b60405190815260200160405180910390f35b6051600080549080607c83609b565b9190505550565b600060208284031215609457600080fd5b5035919050565b60006001820160ba57634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212204ae8109ae428574ea5c6c4840c0c8dcec482287baa69f00b5e4df2bf104a50df64736f6c634300080f0033\",\"v\":\"0x0\",\"r\":\"0x74c7bf4e3ed9069a3dbb573f3c0e98f0b0b343cdcf733c8af23102695317796b\",\"s\":\"0x7be832b3cd5ceae3c65165213f5818bf9350307c490a26c6e5ded1f747363b08\",\"type\":\"0x2\",\"accessList\":[],\"maxPriorityFeePerGas\":\"0xb2d05e00\",\"maxFeePerGas\":\"0xb2d05e10\",\"chainId\":\"0x5\"}"
2022-12-04T20:37:20.139179Z TRACE rpc{method="eth_getTransactionReceipt" params="[\"0xfcf8b4ce53aed1a9c5b900fba738cbd5ffd45b23fcbd4efb7f026cb7ff04e23b\"]"}: ethers_providers::provider: rx="{\"transactionHash\":\"0xfcf8b4ce53aed1a9c5b900fba738cbd5ffd45b23fcbd4efb7f026cb7ff04e23b\",\"transactionIndex\":\"0x1\",\"blockHash\":\"0x433201abbef3437ad893cb0789185280a267a1111f0a0e4689bc5d11edc36926\",\"blockNumber\":\"0x7b36f6\",\"from\":\"0x75045afcc7cd37e6a93513b97baaaa8d0c848e07\",\"to\":null,\"cumulativeGasUsed\":\"0x10d55c\",\"gasUsed\":\"0x1a0df\",\"contractAddress\":\"0x7b5fe55a249ffee4f723b0fa8cb3117a2bca0295\",\"logs\":[],\"status\":\"0x1\",\"logsBloom\":\"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"type\":\"0x2\",\"effectiveGasPrice\":\"0xb2d05e08\"}"
```

Wallaby:

```
$ RUST_LOG=trace forge create --rpc-url https://wallaby.node.glif.io --private-key <private-key> src/Counter.sol:Counter 2>&1 | tee wallaby.log
<tee output>

$ grep 'rpc.*rx' wallaby.log | grep -A500 'eth_sendRawTransaction'
2022-12-04T20:42:45.780626Z TRACE rpc{method="eth_sendRawTransaction" params="[\"0x02f90172827ab71184b2d05e0084b2d05ec884018a71b48080b90116608060405234801561001057600080fd5b5060f78061001f6000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80633fb5c1cb1460415780638381f58a146053578063d09de08a14606d575b600080fd5b6051604c3660046083565b600055565b005b605b60005481565b60405190815260200160405180910390f35b6051600080549080607c83609b565b9190505550565b600060208284031215609457600080fd5b5035919050565b60006001820160ba57634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212204ae8109ae428574ea5c6c4840c0c8dcec482287baa69f00b5e4df2bf104a50df64736f6c634300080f0033c080a0d4b0ebe70fd5067b778835fbd929fd2187747a8f422ed47481193abc66b16ecca062024ce165623ca0568dc10fcfd4a48585d1b25cc1bcd4e191fbff2cd19da832\"]"}: ethers_providers::provider: rx="\"0xf1af1bbb92b9e253481991d7c313b0104adfaa67737721cd186eefb5ddea6cd3\""
2022-12-04T20:42:52.417891Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0xf1af1bbb92b9e253481991d7c313b0104adfaa67737721cd186eefb5ddea6cd3\"]"}: ethers_providers::provider: rx="null"
2022-12-04T20:42:59.064845Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0xf1af1bbb92b9e253481991d7c313b0104adfaa67737721cd186eefb5ddea6cd3\"]"}: ethers_providers::provider: rx="null"
2022-12-04T20:43:05.720576Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0xf1af1bbb92b9e253481991d7c313b0104adfaa67737721cd186eefb5ddea6cd3\"]"}: ethers_providers::provider: rx="null"
2022-12-04T20:43:12.357140Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0xf1af1bbb92b9e253481991d7c313b0104adfaa67737721cd186eefb5ddea6cd3\"]"}: ethers_providers::provider: rx="null"
```

It appears that Wallaby just sends 'null' as the response to `eth_getTransactionByHash` for the pending transaction, and `forge create` just gives up after 4 attempts.

Comparing against the Goerli deploy, it appears that `eth_getTransactionByHash` has a fully formed response for a pending transaction there, except `blockHash`, `blockNumber` and `transactionIndex` are unpopulated until the transaction is executed in a block.

**Comment by raulk** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/9837.

**Comment by jimpick** [comment]
Woot!

```
$ forge create --rpc-url https://wallaby.node.glif.io --private-key <private-key> src/Counter.sol:Counter
[⠰] Compiling...
No files changed, compilation skipped
Deployer: 0x3972E844729522d367BFA1D64368346D7ccEEa59
Deployed to: 0x6F8Ca0Bd11B8C1A802998649B885E2c6E7B49b32
Transaction hash: 0x975e9585c42026ced60e998d36901ffec47a87c780c90ac93a917f44f206411f
```

Works on Wallaby/Carbonado.1

**Comment by DavideSilva** [comment]
Hey @raulk, it seems this issue persists on the Hyperspace testnet. I just went through the trace log like @jimpick  and I found the same behaviour. Using the latest foundry version, `forge 0.2.0 (31f945c 2023-01-30T00:12:20.54706Z)`, the trace logs report back a `null` for the `eth_getTransactionByHash` method.

```
2023-01-30T16:33:32.400611Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0x223de8683313066c7c77fa58ee37b755683bd0446f078e011b32d1188784f021\"]"}: ethers_providers::provider: rx="null"
2023-01-30T16:33:39.230411Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0x223de8683313066c7c77fa58ee37b755683bd0446f078e011b32d1188784f021\"]"}: ethers_providers::provider: rx="null"
2023-01-30T16:33:46.053241Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0x223de8683313066c7c77fa58ee37b755683bd0446f078e011b32d1188784f021\"]"}: ethers_providers::provider: rx="null"
2023-01-30T16:33:52.828211Z TRACE rpc{method="eth_getTransactionByHash" params="[\"0x223de8683313066c7c77fa58ee37b755683bd0446f078e011b32d1188784f021\"]"}: ethers_providers::provider: rx="null"
```

Like Wallaby, this causes Foundry to give up the deployment of the contract.

**Comment by raulk** [comment]
Hey @DavideSilva, I was able to find the transaction through an explorer: https://hyperspace.filfox.info/en/message/0x223de8683313066c7c77fa58ee37b755683bd0446f078e011b32d1188784f021

I was also able to fetch it through Glif's endpoint

```
⟩ curl --location --request POST 'https://api.hyperspace.node.glif.io/rpc/v1' \
      --header 'Content-Type: application/json' \
      --data-raw '{ "jsonrpc":"2.0", "method":"eth_getTransactionByHash", "params":["0x223de8683313066c7c77fa58ee37b755683bd0446f078e011b32d1188784f021"], "id":1 }'
{"jsonrpc":"2.0","result":{"chainId":"0xc45","nonce":"0xf","hash":"0x223de8683313066c7c77fa58ee37b755683bd0446f078e011b32d1188784f021","blockHash":"0xf5263f5c172912763001d775b07d92e0ea71dcc7ec2cb27a6ed365cee840a482","blockNumber":"0xa273","transactionIndex":"0x1","from":"0x895b0bc0f28caacdfac33f747a2bc714edfb04eb","to":null,"value":"0x0","type":"0x2","input":"0x608060405234801561001057600080fd5b50610488806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063431d3fb81461004657806373b4086b14610076578063785f026e146100ca575b600080fd5b61005961005436600461025f565b610147565b6040516001600160a01b0390911681526020015b60405180910390f35b6100aa610084366004610292565b600060208190529081526040902080546001909101546001600160a01b03918216911682565b604080516001600160a01b0393841681529290911660208301520161006d565b6101206100d8366004610292565b604080518082018252600080825260209182018190526001600160a01b0393841681528082528290208251808401909352805484168352600101549092169181019190915290565b6040805182516001600160a01b03908116825260209384015116928101929092520161006d565b600080838360405161015890610236565b6001600160a01b03928316815291166020820152604001604051809103906000f08015801561018b573d6000803e3d6000fd5b506040805180820182526001600160a01b0387811680835287821660208085018281528785166000818152808452889020875181549088166001600160a01b0319918216178255925160019091018054919097169216919091179094558551938452830191909152928101929092529192508291907f786427b4330e2332081142339c333bfd3eaff40ec0587725bb51837e7c57e8049060600160405180910390a150949350505050565b61019e806102b583390190565b80356001600160a01b038116811461025a57600080fd5b919050565b6000806040838503121561027257600080fd5b61027b83610243565b915061028960208401610243565b90509250929050565b6000602082840312156102a457600080fd5b6102ad82610243565b939250505056fe608060405234801561001057600080fd5b5060405161019e38038061019e83398101604081905261002f9161007c565b600080546001600160a01b039384166001600160a01b031991821617909155600180549290931691161790556100af565b80516001600160a01b038116811461007757600080fd5b919050565b6000806040838503121561008f57600080fd5b61009883610060565b91506100a660208401610060565b90509250929050565b60e1806100bd6000396000f3fe6080604052348015600f57600080fd5b506004361060465760003560e01c80632deb210214604b5780639861f3e51460795780639ab11609146089578063bcead63e146099575b600080fd5b600154605d906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b6000546001600160a01b0316605d565b6001546001600160a01b0316605d565b600054605d906001600160a01b03168156fea26469706673582212206ae1ea72e031054c9a2ce828c808c6eda91d990040601506388f61a5704aa63c64736f6c634300080d0033a2646970667358221220ccdc3cd861b70672a4876f30a103017b16d3ce4cda17d118582c0d275f26ad3a64736f6c634300080d0033","gas":"0x18bfd87","maxFeePerGas":"0xb2d05ec8","maxPriorityFeePerGas":"0xb2d05e00","v":"0x0","r":"0x61590de1ebee0596bf851f77735012f1c72c71fdecf030c959e562d88ed17bbe","s":"0x8d9c59a7023ff3f87c129e96bfebed57a49f6c6894360a01c83fa1a562637ed"},"id":1}
```
