### ISSUE TITLE
log's topics is null

### ISSUE THREAD

**Issue by amncjf** [filecoin-project/ref-fvm#1781]
https://api.calibration.node.glif.io/rpc/v1 has obtained the receipt of transaction 0x53b5686d0309e3617e02c8e3f2fe8a5facc14672d746afd948a2db8eb29f292b, where the logIndex is 6 and the topics of the log are null. Why? topics are always not null

**Comment by Stebalien** [comment]
I assume it's LOG0? The topics can definitely be empty.

**Comment by amncjf** [comment]
Yes, https://calibration.filfox.info/en/message/0x53b5686d0309e3617e02c8e3f2fe8a5facc14672d746afd948a2db8eb29f292b. The log index is 6 and this is what happens

**Comment by Stebalien** [comment]
Ok, so this issue is resolved?

**Comment by amncjf** [comment]
No, the problem is not solved, I recommend topics not to return null, but to return [], which is compatible with ethers,web3js,
https://github.com/filecoin-project/lotus/issues/10910

**Comment by Stebalien** [comment]
Understood. In the future:

- Please don't file issues in multiple repos.
- Please do explain what you'd expect to see in the issue description. "log's topics is null" doesn't help us understand the behavior you'd expect.

Closing as a duplicate, let's continue in the lotus issue.
